services:
  vl-backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile.dev
    container_name: venture-launch-backend
    networks:
      - ideaforge-network
    env_file: ./.env.dev
    ports:
      - ${INTERNAL_BACKEND_PORT}:8001
    volumes:
      - ./backend/src:/app/src
    depends_on:
      - vl-database

  vl-database:
    image: postgres:latest
    container_name: venture-launch-database
    networks:
      - ideaforge-network
    env_file: ./.env.dev
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    ports:
      - ${INTERNAL_DATABASE_PORT}:5432
    expose:
      - ${INTERNAL_DATABASE_PORT}
    volumes:
      - database_data:/var/lib/postgresql/data
    restart: on-failure

  rabbitmq:
    image: rabbitmq:3-management
    container_name: venture-launch-rabbitmq
    networks:
      - ideaforge-network
    env_file:
      - ./.env.dev
    ports:
      - ${INTERNAL_RABBITMQ_PORT_A}:5672
      - ${INTERNAL_RABBITMQ_PORT_B}:15672
    expose:
      - ${INTERNAL_RABBITMQ_PORT_A}
      - ${INTERNAL_RABBITMQ_PORT_B}

  rust:
    build:
      context: ./venture-launch-dao
      dockerfile: ./.Dockerfile.dev
    container_name: venture-launch-rust
    networks:
      - ideaforge-network
    env_file: ./venture-launch-dao/.env
    volumes:
      - ./venture-launch-dao/src:/app/src
    depends_on:
      - rabbitmq
      - vl-backend
    restart: on-failure

networks:
  ideaforge-network:
    external: true

volumes:
  database_data:
