FROM node:lts-alpine

WORKDIR /app
COPY package*.json ./ 
RUN npm install

COPY . .

EXPOSE 8001
CMD npm uninstall bcrypt @types/bcrypt \
&& npm install -D @types/bcrypt \
&& npm install bcrypt \
&& npm run dev:nodemon